Product/urls.py
from django.urls import path
from Product.views import detail,detail2,dislike,like,all
app_name = "product"
urlpatterns = [
    path('s/<str:string>/',detail,name="detail"),
    path('<int:id>/',detail2,name="detail2"),
    path('like/<int:id>',like,name="like"),
    path('dislike/<int:id>',dislike,name="dislike"),
    path('all/',all,name="all"),
]

buy/urls.py
from django.urls import path
from buy.views import pay
app_name = "buy"
urlpatterns = [
    path('product_bought/<int:id>/',pay,name="product_bought"),

]

hesab/urls.py
from django.contrib.auth import views
from django.urls import path
from hesab.views import dashboard,courses,statusUser,complete
app_name = "account"
urlpatterns = [
    path('accounts/complete/',complete,name="complete"),
    path('dashboard/',dashboard,name='home'),
    path('courses/',courses,name='courses'),
    path('status/',statusUser,name='status'),
    path("logout/", views.LogoutView.as_view(), name="logout"),

]

home/urls.py
from django.urls import path
from home import views
app_name = "home"

urlpatterns = [
    path('',views.home,name="home"),
    path('about-us',views.about,name="about")
]

spsh/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include("hesab.urls")),
    path('',include("home.urls")),
    path('',include("category.urls")),
    path('',include("buy.urls")),
    path('',include("Product.urls")),
    path('',include("ticket.urls")),
    path('',include("wallet.urls")),

#    path('api-auth/', include('rest_framework.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = "home.views.error404"
# handler500 = "home.views.error500"

ticket/urls.py
from django.urls import path
from ticket.views import ticket,response,ticker
app_name = "ticket"
urlpatterns = [
    path('ticket/',ticket,name='ticket'),
    path('response',response,name='response'),
    path('ticket-datail/<int:id>',ticker,name='ticker'),


]

templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<link rel="stylesheet" type="text/css" href="http://cdn.font-store.ir/behdad.css">
	<style>
		body {
			font-family: 'Behdad', sans-serif !important;
			font-size: 18px !important;
		}
		
		#logo{
			border-radius: 50%;
			height: 50px;
			width:70px;
		}
		{% block style %}{% endblock style %}
	</style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
    <title>{% block title %}{{siteData.nameF}} | {{siteData.nameE}}{% endblock title %}</title>
</head>
    <body dir="rtl">

        <!-- ============================================================== -->
        <!-- Main wrapper - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <div id="main-wrapper">
		
            <!-- ============================================================== -->
            <!-- Top header  -->
            <!-- ============================================================== -->
           <!-- Start Navigation -->
			{% include 'main/navigation.html' %}
			<!-- End Navigation -->
			<div class="clearfix"></div>
			<!-- ============================================================== -->
			<!-- Top header  -->
			<!-- ============================================================== -->
			
			
			{% block body %}{% endblock %}
			<!-- ============================ Pricing Table End ================================== -->
			
			<!-- ============================ Call To Action ================================== -->

			<!-- ============================ Call To Action End ================================== -->
			
			<!-- ============================ Footer Start ================================== -->
			{% include 'main/footer.html' %}
			<!-- ============================ Footer End ================================== -->
			
			<!-- Log In Modal -->
	
			<!-- End Modal -->
			
			<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>
			

		</div>
		<!-- ============================================================== -->
		<!-- End Wrapper -->
		<!-- ============================================================== -->

		<!-- ============================================================== -->
		<!-- All Jquery -->
		<!-- ============================================================== -->
		{% block js %}{% endblock js %}
		<script type="text/javascript" src="{% static '/assets/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/popper.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/select2.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/slick.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/moment.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/daterangepicker.js' %}"></script> 
		<script type="text/javascript" src="{% static '/assets/js/summernote.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/metisMenu.min.js'  %}"></script>	
		<script type="text/javascript" src="{% static '/assets/js/custom.js' %}"></script>
		<!-- ============================================================== -->
		<!-- This page plugins -->
		<!-- ============================================================== -->		


</body>
</html>

templates/main/footer.html
{% load static %}

<hr>
    <section class="bg-cover" style="background:whitesmoke url({% static 'assets/img/call-bg.png' %})no-repeat;">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8 col-md-12 col-sm-12">
                    <div class="call_action mt-4 mb-4 text-center">
                        <h2 class="mb-4 font-2">مشاوره آنلاین !  =D</h2>
                        <p class="mb-4">شما میتونید با استفاده از همکاران ما شخصی سازی شده ی سایت opozex آموزش متناسب با سطح خودتون رو پیدا کنید =) </p>
                        <a href="#" class="btn text-white theme-bg btn-md rounded">شروع چت</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

<footer class="light-footer skin-light-footer style-2">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-5 col-md-5">
                    <div class="footer_widget">
                        <img src="/{{siteData.logo}}" class="img-footer small mb-2" style="border-radius: 50%;" alt="opozex-logo" />
                        {% comment %} <h4 class="extream mb-3 font-2">آیا به کمک تیم پشتیبانی<br>نیاز دارید؟</h4>
                        <p>هر ماه با عضویت در خبرنامه ما از به‌روزرسانی‌ها، معاملات جدید، آموزش‌ها و تخفیف‌ها باخبر شوید.</p> {% endcomment %}
                        <br>
                        <br>
                        عضویت در خبرنامه :
                        <br>
                        <br>
                        <div class="foot-news-last">
                            <div class="input-group">
                              <input type="text" class="form-control" placeholder="ایمیل (غیرفعال)" disabled>
                                <div class="input-group-append">
                                    <button type="button" class="input-group-text theme-bg b-0 text-light" disabled>عضویت</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
               <div class="col-lg-6 col-md-7 ml-auto">
                    <div class="row">
                    
                        <div class="col-lg-4 col-md-4">
                            <div class="footer_widget">
                                <h4 class="widget_title">صفحات</h4>
                                <ul class="footer-menu">
                                    <li><a href="{% url 'home:home' %}">صفحه اصلی</a></li>
                                    <li><a href="{% url 'home:about' %}">درباره ما</a></li>
                                    <li><a href="{% url 'product:all' %}">دوره های آموزشی</a></li>
                                    <li><a href="{% url "ticket:ticket" %}">تماس با ما</a></li>
                                    <li><a href="https://hamrahmodern.com" target="_blank">وبلاگ<span class="update">در حال توسعه</span></a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-4">
                            <div class="footer_widget">
                                <h4 class="widget_title">حساب کاربری</h4>
                                <ul class="footer-menu">
                                    <li><a href="{% url 'account_login' %}">ورود</a></li>
                                    <li><a href="{% url 'account_login' %}">مشاوره رایگان<span class="new">جدید</span></a></li>
                                    
                                    
                                </ul>
                            </div>
                        </div>
                        
                    </div>

            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 col-md-12 text-center">
                    <hr>
                    <p class="mb-0">طراحی شده توسط<a href="https://t.me/yacn_1414/"> (yacn_1414)</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/main/index.html
{% extends 'main/base.html' %}
{% load price_management %}
{% load static %}
{% block body %}

<!-- ============================ Hero Banner  Start================================== -->

<div class="hero_banner image-cover" style="background:#03B97C;height:600px" data-overlay="2">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-9 col-md-10 col-sm-12">
				<div class="simple-search-wrap">
					<div class="hero_search-2 text-center">
						<form method="post">
							{% csrf_token %}
						<h1 class="banner_title mb-4 font-2">میتونی دوره هارو سرچ کنی! <br>( اگه هنوز مطمعن نیستی از کجا شروع کنی راهنمایی رو یه سر بزن )</h1>
						<div class="input-group simple_search">
							<i class="fa fa-search ico"></i>
							<input type="text"  name="search" class="form-control" placeholder="نام دوره آموزشی...">
							<div class="input-group-append">
								<button class="btn theme-bg" type="submit">جستجو</button>
							</div>
						</div>
					</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- ============================ Hero Banner End ================================== -->

<!-- ================================ Tag Award ================================ -->

<!-- ============================ Featured Categories Start ================================== -->

<div class="clearfix"></div>
<!-- ============================ Featured Categories End ================================== -->

<!-- ============================ Latest Cources Start ================================== -->
<hr>
<section class="gray" style="background-color:whitesmoke;">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 col-md-8">
				<div class="sec-heading center">
					<h3 class="font-2">دوره های آموزشی <span style="color:rgb(193, 0, 0)"><i class="fas fa-fire"></i> HOT </span></h3>
					
				</div>
			</div>
		</div>
		
		<div class="row justify-content-center">
		
			<!-- Single Grid -->
			{% for peo in products %}
			<div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
				<div class="crs_grid">
					<div class="crs_grid_thumb">
						<a href="{% url "product:detail" peo.slug %}" class="crs_detail_link">
							<img style="height:auto;" src="{{peo.image}}" class="img-fluid rounded" alt="{{peo.name}}" />
						</a>

					</div>
					<div class="crs_grid_caption">
						<div class="crs_flex">
							<div class="crs_fl_first">
								{% for ca in peo.language.all %}

								<div class="crs_cates"><span>{{ca}}</span></div>

								{% endfor %}
							</div>
							<div class="crs_fl_last">
								<div class="crs_price"><h2><span class="theme-cl">{% takhfif peo.price peo.pricepercent peo.id %}</span><span class="currency">تومان</span></h2></div>
							</div>
						</div>
						<div class="crs_title"><h4><a href="{% url "product:detail" peo.slug %}" class="crs_title_link">{{peo.name}}</a></h4></div>
						<div class="crs_info_detail">
							<ul>
								<li><i class="fas fa-level-up-alt"></i><span>{{peo.tutorial_level}}</span></li>
								
							</ul>
						</div>
					</div>
					<div class="crs_grid_foot">
						<div class="crs_flex">
							<div class="crs_fl_last">
								<div class="foot_list_info">
									<ul class="light">
										<li><div class="elsio_ic"><i class="fa fa-user text-danger"></i></div><div class="elsio_tx">{{peo.student_count}}</div></li>
										<li><div class="elsio_ic"><i class="fa fa-eye text-success"></i></div><div class="elsio_tx">{{peo.view}}</div></li>
										<li><div class="elsio_ic"><i class="fa fa-star text-warning"></i></div><div class="elsio_tx">4.7</div></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>			
			{% endfor %}
			
		</div>
		
		<div class="row justify-content-center">
			<div class="col-lg-7 col-md-8 mt-2">
				<div class="text-center"><a href="{% url "product:all" %}" class="btn btn-md theme-bg-light theme-cl">همه آموزش ها</a></div>
			</div>
		</div>
		
	</div>
</section>
<hr>
<section class="min"  style="background-color:whitesmoke;">
	<div class="container">
	
		<div class="row justify-content-center">
			<div class="col-lg-7 col-md-8">
				<div class="sec-heading center">
					<h3 class="font-2" id="category">دسته بندی های آموزشی <span class="theme-cl">منتخب</span></h3>
					{% comment %} <p>با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.</p> {% endcomment %}
				</div>
			</div>
		</div>
		
		
		<div class="row justify-content-center">
			<!-- Single Category -->
			{% for cat in lang %}
			
			<div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
				<div class="crs_cate_wrap style_2">
					<a href="{% url 'category:category' cat.hashtag %}" class="crs_cate_box">
						<div class="crs_cate_icon"><i class="fa fa-code"></i></div>
						<div class="crs_cate_caption"><span>{{cat}}</span></div>
						{% comment %} <div class="crs_cate_count"><span>22 دوره</span></div> {% endcomment %}
					</a>
				</div>
			</div>
			{% endfor %}
			
		</div>
		
	</div>
</section>
<!-- ============================ articles ================================== -->
<hr>
<section  style="background-color:whitesmoke;">
	<div class="container">
	
		<div class="row justify-content-center">
			<div class="col-lg-7 col-md-10 text-center">
				<div class="sec-heading center mb-4">
					<h3 class="font-2">لیست مقالات <span style="color: brown;">پیشنهادی</span></h3>
				
				</div>
			</div>
		</div>
		
		<div class="row justify-content-center">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
				<div class="tutor-slide">
				{% for blog_item in blog %}
					<!-- Single Item -->
					<div class="lios_item">	
						<div class="crs_trt_grid theme-light shadow_none">
							<div class="crs_trt_thumb">
								<a href="instructor-detail.html" class="crs_trt_thum_link"><img src="{{blog_item.image}}" class="img-fluid" alt=""></a>
							</div>
							<div class="crs_trt_caption large"  style="background-color: white;">
								{% for ca in blog_item.category.all %}

								<div class="instructor_tag dark"><span>{{ca}}</span></div>
								{% endfor %}
								<div class="instructor_title"><h4><a href="#">{{blog_item}}</a></h4></div>
								{% comment %} <div class="trt_rate_inf">
									<i class="fa fa-star filled"></i>
									<i class="fa fa-star filled"></i>
									<i class="fa fa-star filled"></i>
									<i class="fa fa-star filled"></i>
									<i class="fa fa-star-half filled"></i>
									<span class="alt_rates">(244 نظر ثبت شده)</span>
								</div> {% endcomment %}
								<a class="crs_title_link" tabindex="0">
									{{blog_item.caption|truncatechars:250}}
								</a>
							</div>
						</div>
					</div>
					<!-- End Single Item -->
					{% endfor %}
				</div>
			</div>
		</div>
		
	</div>
</section>
<hr>
<!-- ============================ end articles ================================== -->


<div class="clearfix"></div>
<!-- ============================ Work Process End ================================== -->

<!-- ============================ Our Instructor Start ================================== -->

<!-- ============================ Our Instructor End ================================== -->

<!-- ============================ Pricing Table ================================== -->

{% endblock body %}

templates/main/navigation.html
<style>
    #logo{
        border-radius: 50%;
        height: 50px;
        width:70px;
    }
</style>
<div class="header head-shadow">
    <div class="container">
        <nav id="navigation" class="navigation navigation-landscape">
            <div class="nav-header">
                <a class="nav-brand" href="{% url 'home:home' %}">
                    <img src="/{{siteData.logo}}" id="logo" class="logo" alt="logo" />
                </a>
                <div class="nav-toggle"></div>
                <div class="mobile_nav">
                    <ul>
                        {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'account:home' %}">
                                <span class="embos_45"><i class="fas fa-sign-in-alt ml-1 rotate-img"></i>داشبورد ({{request.user}})</span>
                            </a>
                        </li>									
                
                        {% else %}
                        <li>
                            <a href="{% url 'account_login' %}">
                                <span class="embos_45"><i class="fas fa-sign-in-alt ml-1 rotate-img"></i>ورود</span>
                            </a>
                        </li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>
            <div class="nav-menus-wrapper">
                <ul class="nav-menu">
                
                    <li class="active"><a href="{% url 'home:home' %}">خانه<span class="submenu-indicator"></span></a></li>
                    
                    <li><a href="#category">دسته بندی های آموزشی<span class="submenu-indicator"></span></a>
                        <ul class="nav-dropdown nav-submenu">
                            {% for categ in category %}
                            <li><a href="#">{{categ.name}}<span class="submenu-indicator"></span></a>
                                <ul class="nav-dropdown nav-submenu">
                                    {% for lan in lang %}
                                    {% for cat in lan.category.all %}
                                    {% if cat.name == categ.name %}
                                    <li><a href="/category/{{lan.hashtag}}">{{lan.nameE}}</a></li>
                                    {% endif %}
                                    {% endfor %}
                                    {% endfor %}

                                </ul>
                            </li>
                            {% endfor %}
        
                        </ul>
                    </li>
                    <li><a href="#">مشاوره رایگان</a></li>
                    
                            
                            
                        
                </ul>
                <ul class="nav-menu nav-menu-social align-to-left">
                    {% if request.user.is_authenticated %}
                    
                    <li class="add-listing bg-white"><a href="{% url 'account:home' %}">داشبورد</a></li>
                    <li class="add-listing bg-white"><a href="{% url 'account:courses' %}">دوره های شما</a></li>

                    {% else %}

                    <li>
                        <a href="{% url 'account_login' %}">
                            <i class="fas fa-sign-in-alt ml-1 rotate-img"></i><span class="dn-lg">ورود</span>
                        </a>
                    </li>
                    <li class="add-listing bg-white">
                        <a href="{% url 'account_signup' %}" class="text-white">ثبت نام</a>
                    </li>
                    {% endif %}
                    
                
                    
                </ul>
            </div>
        </nav>
    </div>
</div>

templates/main/searchHome.html
{% extends 'main/base.html' %}
{% load static %}
{% load price_management %}
{% block body %}

<section class="gray" style="background-color:whitesmoke;">
	<div class="container">
		<div class="row justify-content-center">
			<div class="simple-search-wrap text-right">
					<div class="hero_search-2">
						<form method="post">
						
							<h4 class="font-lg mb-4">یادت نرفته که قبلش میتونی از راهنمایی کمک بگیری ؟ باهاش میتونی دوره مناسب خودتو پیدا کنی :)</h4>
							{% csrf_token %}
						<div class="input-group simple_search">
							<i class="fa fa-search ico"></i>
							<input type="text" name="search" class="form-control" placeholder="جستجو دوره آموزش...">
							<div class="input-group-append">
								<button class="btn theme-bg" type="submit">جستجو</button>
							</div>
						</div>
					
					</form>
					</div>
				</div>
			<div class="col-lg-7 col-md-8">
				<div class="sec-heading center">
				<br>
				<br>
					<h3 class="font-2">نتایج جستجوی : {{text}} </h3>
				</div>
			</div>
		</div>
		
		<div class="row justify-content-center">
		
{% for pe in res %}
			<div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
				<div class="crs_grid">
					<div class="crs_grid_thumb">
						<a href="{% url "product:detail" pe.slug %}" class="crs_detail_link">
							<img src="{{pe.image}}" class="img-fluid rounded" alt="{{pe.name}}" />
						</a>

						<div class="crs_locked_ico">
							<i class="fa fa-lock"></i>
						</div>
					</div>
					<div class="crs_grid_caption">
						<div class="crs_flex">
							<div class="crs_fl_first">
								{% for ca in pe.language.all %}

								<div class="crs_cates"><span>{{ca}}</span></div>

								{% endfor %}
							</div>
							<div class="crs_fl_last">
								<div class="crs_price"><h2><span class="theme-cl">{% takhfif pe.price pe.pricepercent pe.id %}</span><span class="currency">تومان</span></h2></div>
							</div>
						</div>
						<div class="crs_title"><h4><a href="{% url "product:detail" pe.slug %}" class="crs_title_link">{{pe.name}}</a></h4></div>
						<div class="crs_info_detail">
							<ul>
								<li><i class="fa fa-level-up-alt"></i><span>{{pe.tutorial_level}}</span></li>
								
							</ul>
						</div>
					</div>
					<div class="crs_grid_foot">
						<div class="crs_flex">
						
							<div class="crs_fl_last">
								<div class="foot_list_info">
									<ul class="light">
										<li><div class="elsio_ic"><i class="fa fa-user text-danger"></i></div><div class="elsio_tx">{{pe.student_count}}</div></li>
										<li><div class="elsio_ic"><i class="fa fa-eye text-success"></i></div><div class="elsio_tx">{{pe.view}}</div></li>
										<li><div class="elsio_ic"><i class="fa fa-star text-warning"></i></div><div class="elsio_tx">4.7</div></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
{% endfor %}

			
		</div>
		
		<div class="row justify-content-center">
			<div class="col-lg-7 col-md-8 mt-2">
				<div class="text-center"><a href="{% url 'product:all' %}" class="btn btn-md theme-bg-light theme-cl">همه آموزش ها</a></div>
			</div>
		</div>
		
	</div>
</section>
{% endblock body %}