Product/urls.py
from django.urls import path
from Product.views import detail,detail2,dislike,like,all
app_name = "product"
urlpatterns = [
    path('s/<str:string>/',detail,name="detail"),
    path('<int:id>/',detail2,name="detail2"),
    path('like/<int:id>',like,name="like"),
    path('dislike/<int:id>',dislike,name="dislike"),
    path('all/',all,name="all"),
]

buy/urls.py
from django.urls import path
from buy.views import pay
app_name = "buy"
urlpatterns = [
    path('product_bought/<int:id>/',pay,name="product_bought"),

]

category/urls.py
from django.urls import path
from category import views
app_name = "category"
urlpatterns = [
    path('category/<str:inp>',views.categoryList,name="category"),
    path('filter/<str:inp>',views.filterCat,name="filterCategory"),
]

home/urls.py
from django.urls import path
from home import views
app_name = "home"

urlpatterns = [
    path('',views.home,name="home"),
    path('about-us',views.about,name="about")
]

spsh/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include("hesab.urls")),
    path('',include("home.urls")),
    path('',include("category.urls")),
    path('',include("buy.urls")),
    path('',include("Product.urls")),
    path('',include("ticket.urls")),
    path('',include("wallet.urls")),

#    path('api-auth/', include('rest_framework.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = "home.views.error404"
# handler500 = "home.views.error500"

category/models/categories.py
from django.db import models

class Category(models.Model):
    name = models.CharField("اسم دسته بندی", max_length=50)
    hashtag = models.CharField("هشتگ انگلیسی", max_length=50)
    status = models.BooleanField("وضعیت",default=False)


    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        

category/models/language.py
from django.db import models

class Languages(models.Model):
    nameE = models.CharField("نام زبان", max_length=50)
    nameF = models.CharField("فارسیش",max_length=50)
    status = models.BooleanField("وضعیت",default=False)
    hashtag = models.CharField("هشتگ انگلیسی", max_length=50)
    category = models.ManyToManyField("category.Category", verbose_name="ذسته بندس ها")
    def __str__(self):
        return self.nameE

    class Meta:
        verbose_name = "زبان برنامه نویسی"
        verbose_name_plural = "زبان ها"
        

category/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from category.models import Category,Languages
from home.models import informationSite
from Product.models import Product
from category.filters import ProductFilter

def categoryList(request,inp):
    languagess = Languages.objects.all()
    category = Category.objects.all()
    cat = get_object_or_404(Languages, hashtag=inp)
    pr = Product.objects.filter(published=True)
    categoryname = Product.objects.filter(published=True).filter(language__hashtag=inp)
    siteData = informationSite.objects.first()
    paginator = Paginator(categoryname, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,"category/full-category.html",{
    "inp":cat,
    "category":category,
    "lang":languagess,
    "siteData":siteData,
    "product":pr,
    "page":paginator,
    "categoryname":page_obj,
    })

def filterCat(request,inp):
    languagess = Languages.objects.all()
    category = Category.objects.all()
    cat = get_object_or_404(Languages, nameE=inp)
    siteData = informationSite.objects.first()
    categoryname = Product.objects.filter(published=True).filter(language__nameE=inp)
    pr = Product.objects.filter(published=True)
    paginator = Paginator(categoryname, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    if request.POST:
        categoryname = ProductFilter(request.POST,queryset=Product.objects.all())
        return render(request,'category/filter-category.html',{
            "inp":cat,
            "category":category,
            "siteData":siteData,
            "lang":languagess,
            "product":pr,
            'form':ProductFilter,
            # "page":paginator,
            "categoryname":categoryname.qs,
            })
    return render(request,'category/filter-category.html',{
    "inp":cat,
    "category":category,
    "siteData":siteData,
    "lang":languagess,
    "product":pr,
    'form':ProductFilter,
    "page":paginator,
    "categoryname":page_obj,
})

templates/category/filter-category.html
{% load static %}
{% load price_management %}
{% load get_item %}
{% load widget_tweaks %}


<!DOCTYPE html>
<html lang="fa">
	
<head>
		<meta charset="utf-8" />
		<meta name="author" content="Themezhub" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>دسته بندی - {{inp}}</title>

        <!-- Custom CSS -->
        <link type="text/css" href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
		
    </head>
	
    <body dir="rtl">

        <!-- ============================================================== -->
        <!-- Main wrapper - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <div id="main-wrapper">
		
            <!-- ============================================================== -->
            <!-- Top header  -->
            <!-- ============================================================== -->
            <!-- Start Navigation -->
     {% include "main/navigation.html" %}
			<!-- End Navigation -->
			<div class="clearfix"></div>
			<!-- ============================================================== -->
			<!-- Top header  -->
			<!-- ============================================================== -->
			
			<!-- ============================ Page Title Start================================== -->
			<section class="page-title">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							
							<div class="breadcrumbs-wrap">
								<h1 class="breadcrumb-title font-2">دسته بندی - {{inp}}</h1>
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb p-0 bg-white">
										<li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
										<li class="breadcrumb-item active theme-cl" aria-current="page">{{inp}}</li>
									</ol>
								</nav>
							</div>
							
						</div>
					</div>
				</div>
			</section>
			<!-- ============================ Page Title End ================================== -->
			
			<!-- ============================ All Cources ================================== -->
			<section class="gray" style="background-color:whitesmoke;">
				<div class="container">
					<div class="row">
					
                        <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
							<div class="page-sidebar p-0">
								<a class="filter_links" data-toggle="collapse" href="#fltbox" role="button" aria-expanded="false" aria-controls="fltbox">فیلتر پیشرفته<i class="fa fa-sliders-h mr-2"></i></a>							
								<form method="post" >
								<div class="collapse" id="fltbox">
									<!-- Find New Property -->
									<div class="sidebar-widgets p-4">
										
										<div class="form-group">
											<div class="input-with-icon">

												{% render_field form.form.title class="form-control" placeholder="نام دوره" %}
												<i class="ti-search"></i>
											</div>
										</div>
										

										
										
										
										<div class="form-group">
											<h6>سطح مهارت</h6>
											<ul class="no-ul-list mb-3">
												{{form.form.tutorial_level|add_class:"form-control"}}

											</ul>
										</div>
										
										<div class="form-group">
											<h6>قیمت</h6>
											<ul class="no-ul-list mb-3">
												{{form.form.price|add_class:"form-control"}}

											</ul>
										</div>
										
										<div class="row">
											<div class="col-lg-12 col-md-12 col-sm-12 pt-4">
												<button type="submit" class="btn theme-bg rounded full-width">فیلتر</button>
											</div>
										</div>
										
									</div>
									{% csrf_token %}
								</form>
								</div>
							</div>
                        </div>

						<!-- Content -->
						<div class="col-xl-8 col-lg-8 col-md-12 col-sm-12">
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12">
									<div class="short_wraping">
										<div class="row m-0 align-items-center justify-content-between">
										
											<div class="col-lg-4 col-md-5 col-sm-12  col-sm-6">
												<div class="shorting_pagination_laft">
                                                    <h6 class="m-0"> {% if request.POST %}{{categoryname.count}}{% else %}{{ categoryname }}{% endif %}</h6>
												</div>
											</div>
								
										</div>
									</div>
								</div>
							</div>
	
							<div class="row justify-content-center">
                                {% for pro in categoryname %}
								<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
									<div class="crs_grid shadow_none brd">
										<div class="crs_grid_thumb">
											<a href="{% url 'product:detail' pro.slug %}" class="crs_detail_link">
												<img style="height:auto;" src="/{{pro.image}}" class="img-fluid rounded" alt="{{pro.slug}}">
											</a>
											<div class="crs_locked_ico">
												<i class="fa fa-lock"></i>
											</div>
										</div>
										<div class="crs_grid_caption">
											<div class="crs_flex">
												<div class="crs_fl_first">
                                                    {% for ca in pro.language.all %}
													<div class="crs_cates cl_8"><span>{{ca}}</span></div>
                                            {% endfor %}
												
												</div>
												<div class="crs_fl_last">
													<div class="crs_inrolled"><strong>{{pro.view}}</strong>بازدید</div>
												</div>
											</div>
											<div class="crs_title"><h4><a href="{% url 'product:detail' pro.id %}/" class="crs_title_link">{{ pro.name }}</a></h4></div>
											<h6>{{pro.small_description|truncatechars:150}}</h6>
											<div class="crs_info_detail">
												<ul>
													<li><i class="fa fa-file-pdf"></i><span>{{pro.tutorial}}</span></li>
													
													<li><i class="fa fa-signal text-warning"></i><span>{{pro.tutorial_level}}</span></li>
												</ul>
											</div>
										</div>
										<div class="crs_grid_foot">
											<div class="crs_flex">
										
												<div class="crs_fl_last">
													<div class="crs_price">{% if pro.price_percent > 0 %}<span style="color:red">{{pro.price_percent}}٪  تخفیف</span>{% endif %}<h2><span class="theme-cl">{% takhfif pro.price pro.pricepercent pro.id %}</span><span class="currency">تومان</span></h2></div>
												</div>
											</div>
										</div>
									</div>
								</div>
							    {% endfor %}
							
							</div>
							
							<!-- Pagination -->
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12">
									<ul class="pagination p-center">
		
										
			{% for pagination in page %}
									
										<li class="page-item"><a class="page-link bg-dark" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
									
									
			{% endfor %}
									</ul>
							</div> 
								
						</div>
							
						</div>
					
					</div>
				</div>
			</section>
			<!-- ============================ All Cources ================================== -->
			
			<!-- ============================ Call To Action ================================== -->
	
			<!-- ============================ Call To Action End ================================== -->
			
			<!-- ============================ Footer Start ================================== -->
			{% include 'main/footer.html' %}
			<!-- ============================ Footer End ================================== -->
			
			<!-- Log In Modal -->
		
			<!-- End Modal -->
			
			<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>
			

		</div>
		<!-- ============================================================== -->
		<!-- End Wrapper -->
		<!-- ============================================================== -->

		<!-- ============================================================== -->
		<!-- All Jquery -->
		<!-- ============================================================== -->
        <script type="text/javascript" src="{% static 'assets/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/popper.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/select2.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/slick.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/moment.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/daterangepicker.js' %}"></script> 
		<script type="text/javascript" src="{% static 'assets/js/metisMenu.min.js' %}"></script>	
		<script type="text/javascript" src="{% static 'assets/js/summernote.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/custom.js' %}"></script>
		<!-- ============================================================== -->
		<!-- This page plugins -->
		<!-- ============================================================== -->		

	</body>

</html>

templates/category/full-category.html
{% load static %}
{% load price_management %}
<!DOCTYPE html>
<html lang="fa">
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>دسته بندی - {{inp}}</title>
		 
        <!-- Custom CSS -->
        <link type="text/css" href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
		
    </head>
	
    <body dir="rtl">

        <!-- ============================================================== -->
        <!-- Main wrapper - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <div id="main-wrapper">
		
            <!-- ============================================================== -->
            <!-- Top header  -->
            <!-- ============================================================== -->
            <!-- Start Navigation -->
			
			{% include "main/navigation.html" %}

			<!-- End Navigation -->
			<div class="clearfix"></div>
			<!-- ============================================================== -->
			<!-- Top header  -->
			<!-- ============================================================== -->
			
			<!-- ============================ Page Title Start================================== -->
			<section class="page-title">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							
							<div class="breadcrumbs-wrap">
								<h1 class="breadcrumb-title font-2">دسته بندی - {{inp}}</h1>
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb p-0 bg-white">
										<li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
										<li class="breadcrumb-item active theme-cl" aria-current="page">{{inp}}</li>
									</ol>
								</nav>
							</div>
							
						</div>
					</div>
				</div>
			</section>
			<!-- ============================ Page Title End ================================== -->
			
			<!-- ============================ Course Detail ================================== -->
			<section class="gray" style="background-color:whitesmoke;">
				<div class="container">
					<div class="row">
					
						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="short_wraping">
								<div class="row m-0 align-items-center justify-content-between">
								
									<div class="col-lg-4 col-md-5 col-sm-12  col-sm-6">
										<div class="shorting_pagination_laft">
											<h6 class="m-0"> {{ categoryname }}</h6>
										</div>
									</div>
							
									<div class="col-lg-8 col-md-7 col-sm-12 col-sm-6">
										<div class="dlks_152">
											<a href="{% url 'category:filterCategory' inp %}"><button class="btn theme-bg">فیلتر</button></a>

									
										</div>
									</div>
								</div>
							</div>
						</div>
					
					</div>
					
					<div class="row justify-content-center">
						{% for pro in categoryname %}
						<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
							<div class="crs_grid_list">
								
								<div class="crs_grid_list_thumb">
									<a href="{% url 'product:detail' pro.slug %}"><img src="/{{pro.image}}" class="img-fluid rounded" alt="{{pro.name}}"></a>
								</div>
								
								<div class="crs_grid_list_caption">
									<div class="crs_lt_101">
										{% for ca in pro.language.all %}
										<span class="est st_{{forloop.counter}}">{{ca}}</span>
								{% endfor %}
									</div>
									<div class="crs_lt_102">
										<a href="{% url 'product:detail' pro.slug %}"><h4 class="crs_tit">{{ pro.name }}</h4></a>
									</div>
									<div class="crs_lt_103">
										<div class="crs_info_detail">
											<ul>
												
												<li><i class="fa fa-user"></i><span>{{pro.student_count}} دانشجو</span></li>
												<li><i class="fa fa-eye"></i><span>{{pro.view}} بازدید</span></li>
											</ul>
										</div>
									</div>
									<div class="crs_flex">
										<div class="crs_fl_first">
											<div class="crs_price">{% if pro.price_percent > 0 %}<span style="color:red">{{pro.price_percent}}٪  تخفیف</span>{% endif %}<h2><span class="theme-cl">{% takhfif pro.price pro.pricepercent pro.id %}</span><span class="currency">هزار تومان</span></h2></div>
										</div>
										<div class="crs_fl_last">
											<div class="crs_linkview"><a href="{% url 'buy:product_bought' pro.id %}" class="btn btn_view_detail theme-bg text-light">ثبت نام</a></div>
										</div>
									</div>
								</div>
								
							</div>
						</div>

						{% endfor %}
						
					</div>
			
								<!-- Pagination -->
<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12">
							<ul class="pagination p-center">

								
	{% for pagination in page %}
							
								<li class="page-item"><a class="page-link bg-dark" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
							
							
	{% endfor %}
							</ul>
					</div> 
						
				</div>
			</section>
			<!-- ============================ Course Detail ================================== -->
			
			<!-- ============================ Call To Action ================================== -->
	
			<!-- ============================ Call To Action End ================================== -->
			
			<!-- ============================ Footer Start ================================== -->
			{% include 'main/footer.html' %}
			<!-- ============================ Footer End ================================== -->
			
			<!-- Log In Modal -->
	
			<!-- End Modal -->
			
			<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>
			

		</div>
		<!-- ============================================================== -->
		<!-- End Wrapper -->
		<!-- ============================================================== -->

		<!-- ============================================================== -->
		<!-- All Jquery -->
		<!-- ============================================================== -->
		<script type="text/javascript" src="{% static 'assets/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/popper.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/select2.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/slick.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/moment.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/daterangepicker.js' %}"></script> 
		<script type="text/javascript" src="{% static 'assets/js/metisMenu.min.js' %}"></script>	
		<script type="text/javascript" src="{% static 'assets/js/summernote.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/custom.js' %}"></script>
		<!-- ============================================================== -->
		<!-- This page plugins -->
		<!-- ============================================================== -->		

	</body>

</html>