buy/urls.py
from django.urls import path
from buy.views import pay
app_name = "buy"
urlpatterns = [
    path('product_bought/<int:id>/',pay,name="product_bought"),

]

hesab/urls.py
from django.contrib.auth import views
from django.urls import path
from hesab.views import dashboard,courses,statusUser,complete
app_name = "account"
urlpatterns = [
    path('accounts/complete/',complete,name="complete"),
    path('dashboard/',dashboard,name='home'),
    path('courses/',courses,name='courses'),
    path('status/',statusUser,name='status'),
    path("logout/", views.LogoutView.as_view(), name="logout"),

]

home/urls.py
from django.urls import path
from home import views
app_name = "home"

urlpatterns = [
    path('',views.home,name="home"),
    path('about-us',views.about,name="about")
]

spsh/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include("hesab.urls")),
    path('',include("home.urls")),
    path('',include("category.urls")),
    path('',include("buy.urls")),
    path('',include("Product.urls")),
    path('',include("ticket.urls")),
    path('',include("wallet.urls")),

#    path('api-auth/', include('rest_framework.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = "home.views.error404"
# handler500 = "home.views.error500"

ticket/urls.py
from django.urls import path
from ticket.views import ticket,response,ticker
app_name = "ticket"
urlpatterns = [
    path('ticket/',ticket,name='ticket'),
    path('response',response,name='response'),
    path('ticket-datail/<int:id>',ticker,name='ticker'),


]

wallet/urls.py
from django.urls import path
from wallet.views import walletCenter,afzayesh
app_name = "Wallet"
urlpatterns = [
    path("wallet/",walletCenter,name="wallet"),
    path("afzayesh/",afzayesh,name="pay_afzayesh"),
]

templates/detail/all.html
{% load static %}
{% load price_management %}
{% load get_item %}
{% load widget_tweaks %}


<!DOCTYPE html>
<html lang="fa">
	
<head>
		<meta charset="utf-8" />
		<meta name="author" content="Themezhub" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>همه محصولات</title>

        <!-- Custom CSS -->
        <link type="text/css" href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
		
    </head>
	
    <body dir="rtl">

        <!-- ============================================================== -->
        <!-- Main wrapper - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <div id="main-wrapper">
		
            <!-- ============================================================== -->
            <!-- Top header  -->
            <!-- ============================================================== -->
            <!-- Start Navigation -->
     {% include "main/navigation.html" %}
			<!-- End Navigation -->
			<div class="clearfix"></div>
			<!-- ============================================================== -->
			<!-- Top header  -->
			<!-- ============================================================== -->
			
			<!-- ============================ Page Title Start================================== -->
			<section class="page-title">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12">
							
							<div class="breadcrumbs-wrap">
								<h1 class="breadcrumb-title font-2">همه محصولات</h1>
								<nav aria-label="breadcrumb">
									<ol class="breadcrumb p-0 bg-white">
										<li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
										<li class="breadcrumb-item active theme-cl" aria-current="page">همه محصولات</li>
									</ol>
								</nav>
							</div>
							
						</div>
					</div>
				</div>
			</section>
			<!-- ============================ Page Title End ================================== -->
			
			<!-- ============================ All Cources ================================== -->
			<section class="gray">
				<div class="container">
					<div class="row">
					

						<!-- Content -->
						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12">
									<div class="short_wraping">
										<div class="row m-0 align-items-center justify-content-between">
										
											<div class="col-lg-4 col-md-5 col-sm-12  col-sm-6">
												<div class="shorting_pagination_laft">
                                                    <h6 class="m-0"> {% if request.POST %}{{categoryname.count}}{% else %}{{ categoryname }}{% endif %}</h6>
												</div>
											</div>
								
										</div>
									</div>
								</div>
							</div>
	
							<div class="row justify-content-center">
                                {% for pro in categoryname %}
								<div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
									<div class="crs_grid shadow_none brd">
										<div class="crs_grid_thumb">
											<a href="{% url 'product:detail' pro.id %}/" class="crs_detail_link">
												<img src="/{{pro.image}}" class="img-fluid rounded" alt="{{pro.slug}}">
											</a>
											<div class="crs_locked_ico">
												<i class="fa fa-lock"></i>
											</div>
										</div>
										<div class="crs_grid_caption">
											<div class="crs_flex">
												<div class="crs_fl_first">
                                                    {% for ca in pro.language.all %}
													<div class="crs_cates cl_8"><span>{{ca}}</span></div>
                                            {% endfor %}
												
												</div>
												<div class="crs_fl_last">
													<div class="crs_inrolled"><strong>{{pro.view}}</strong>بازدید</div>
												</div>
											</div>
											<div class="crs_title"><h4><a href="{% url 'product:detail' pro.id %}/" class="crs_title_link">{{ pro.name }}</a></h4></div>
											<h6>{{pro.small_description|truncatechars:150}}</h6>
											<div class="crs_info_detail">
												<ul>
													<li><i class="fa fa-file-pdf"></i><span>{{pro.tutorial}}</span></li>
													
													<li><i class="fa fa-signal text-warning"></i><span>{{pro.tutorial_level}}</span></li>
												</ul>
											</div>
										</div>
										<div class="crs_grid_foot">
											<div class="crs_flex">

												<div class="crs_fl_last">
													<div class="crs_price">{% if pro.price_percent > 0 %}<span style="color:red">{{pro.price_percent}}٪  تخفیف</span>{% endif %}<h2><span class="theme-cl">{% takhfif pro.price pro.pricepercent pro.id %}</span><span class="currency">تومان</span></h2></div>
												</div>
											</div>
										</div>
									</div>
								</div>
							    {% endfor %}
							
							</div>
							
							<!-- Pagination -->
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12">
									<ul class="pagination p-center">
		
										
			{% for pagination in page %}
									
										<li class="page-item"><a class="page-link bg-dark" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
									
									
			{% endfor %}
									</ul>
							</div> 
								
						</div>
							
						</div>
					
					</div>
				</div>
			</section>
			<!-- ============================ All Cources ================================== -->
			
			<!-- ============================ Call To Action ================================== -->
	
			<!-- ============================ Call To Action End ================================== -->
			
			<!-- ============================ Footer Start ================================== -->
			{% include 'main/footer.html' %}
			<!-- ============================ Footer End ================================== -->
			
			<!-- Log In Modal -->
		
			<!-- End Modal -->
			
			<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>
			

		</div>
		<!-- ============================================================== -->
		<!-- End Wrapper -->
		<!-- ============================================================== -->

		<!-- ============================================================== -->
		<!-- All Jquery -->
		<!-- ============================================================== -->
        <script type="text/javascript" src="{% static 'assets/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/popper.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/select2.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/slick.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/moment.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/daterangepicker.js' %}"></script> 
		<script type="text/javascript" src="{% static 'assets/js/metisMenu.min.js' %}"></script>	
		<script type="text/javascript" src="{% static 'assets/js/summernote.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'assets/js/custom.js' %}"></script>
		<!-- ============================================================== -->
		<!-- This page plugins -->
		<!-- ============================================================== -->		

	</body>

</html>

templates/detail/contact.html
{% load static %}
{% load widget_tweaks %}
{% load price_management %}
<!DOCTYPE html>
<html lang="fa">
	
<head>
		<meta charset="utf-8" />
		<meta name="author" content="Themezhub" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>ارتباط با ما</title>
		
        <!-- Custom CSS -->
        <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
		<style>
            .gray{
                background: #f7f8f9;
            }
            
        </style>
    </head>
	
    <body class="blog-page" dir="rtl" style="background:#f7f8f9;">

        <!-- ============================================================== -->
        <!-- Main wrapper - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <div id="main-wrapper">
		
            <!-- ============================================================== -->
            <!-- Top header  -->
            <!-- ============================================================== -->
            <!-- Start Navigation -->
            {% include 'main/navigation.html' %}

			<!-- End Navigation -->
			<div class="clearfix"></div>
			<!-- ============================================================== -->
			<!-- Top header  -->
			<!-- ============================================================== -->
			
			<!-- ============================ Page Title Start================================== -->
			<section class="page-title gray" style="background: whitesmoke;">
				<div class="container-fluid">
					<div class="row">
						<div class="col-lg-3 col-md-3">
							<div class="dashboard-navbar" style="border-radius: 20px;">
								
								<div class="d-user-avater">
									<img src="/{{request.user.profile}}" class="img-fluid avater" alt="">
									<h4>{{request.user.username}}</h4>
									{% comment %} <span>برنامه نویس ارشد</span> {% endcomment %}
									<div class="elso_syu89">
										<ul>
											<li><a href="https://www.twitter.com/opozex"><i class="ti-twitter"></i></a></li>
											<li><a href="https://www.instagram.com/opozex"><i class="ti-instagram"></i></a></li>
										</ul>
									</div>
									<div class="elso_syu77">
										<div class="one_third"><div class="one_45ic text-warning bg-light-warning"><i class="fas fa-star"></i></div><span>امتیازات</span></div>
										<div class="one_third"><a href="{% url 'account:courses' %}"><div class="one_45ic text-success bg-light-success"><i class="fas fa-file-invoice"></i></div><span>دوره ها</span></a></div>
										<div class="one_third"><div class="one_45ic text-purple bg-light-purple"><i class="fas fa-user"></i></div><span>هنرجویان</span></div>
									</div>
								</div>
								
								<div class="d-navigation">
									<ul id="side-menu">
										<li><a href="{% url 'account:home' %}"><i class="fas fa-th"></i>داشبورد</a></li>
										<li><a href="{% url 'Wallet:wallet' %}" style="font-family: sans-serif;"><i class="fas fa-credit-card"></i>کیف پول ({% if bal == 0 %}0 {% else %}{% format balance %}{% endif %})</a></li>
						
										<li><a href="{% url "ticket:ticket" %}"><i class="fas fa-comment"></i>تیکت</a></li>
										<li class="active">
											<a href="{% url 'account:courses' %}"><i class="fas fa-shopping-cart"></i>دوره های خریداری شده</a>
										
										</li>
										<li>
											<!-- <a href="{% url 'account_email' %}"> -->
												<a href="{% url 'account_email' %}">
												<i class="fas fa-envelope"></i>تغییر ایمیل</a>
											
										</li>
										<li>
											<a href="{% url 'account:status' %}"><i class="fas fa-history"></i>تاریخچه ی خرید و انتقالات</a>
											
										</li>
							
										<li>
											<a href="{% url 'account_change_password' %}"><i class="fas fa-key ml-1 rotate-img"></i>تغییر رمز عبور</span></a>
											
										</li>
										<li>
											<form action="{% url 'account:logout' %}" method="post">
												{% csrf_token %}
												<button type="submit" class="btn btn-danger">Logout</button>
											</form>
										</li>
									</ul>
								</div>
								
							</div>
						</div>
						<div class="col-xl-4 col-lg-6 col-md-12 col-sm-12">
							<div class="form-group">
								<h4>با ما در ارتباط باشید</h4>
								<span>همه جوره کمکی از دستمون بربیاد دریغ نمیکنیم :))) </span>
							</div>
							<div class="row">
								<form method="post">
									{% csrf_token %}
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
								
								<select class="form-select" name="subject" multiple aria-label="multiple select example" required>
									<option value="license">درخواست لایسنس جدید</option>
									<option value="course">درباره دوره ها</option>
									<option value="bug">گزارش باگ</option>
								  </select>
								</div>

								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
									<br>
									<br>
									{% render_field form.text class="form-control" %}

								</div>
								<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
									<br>
									<br>
									<div class="form-group">
										<button class="btn theme-bg text-white btn-md" type="submit">ارسال پیام</button>
									</div>
								</div>
							</div>
						</form>
						</div>
						
						<div class="col-xl-5 col-lg-5 col-md-12 col-sm-12">
							<div class="lmp_caption pr-lg-5">
								<ol class="list-unstyled p-0">
								  {% comment %} <li class="d-flex align-items-start my-3 my-md-4">
									<div class="rounded-circle p-3 p-sm-4 d-flex align-items-center justify-content-center theme-bg-light">
									  <div class="position-absolute theme-cl h5 mb-0"><i class="fas fa-home"></i></div>
									</div>
									<div class="mr-3 mr-md-4">
									  <h4>آدرس ما</h4>
									  <p>
										ایران، تهران،<br>میدان آزادی، جنب مترو شادمان<br>مجتمع صدف پلاک 8
									  </p>
									</div>
								  </li> {% endcomment %}
								  <li class="d-flex align-items-start my-3 my-md-4">
									<div class="rounded-circle p-3 p-sm-4 d-flex align-items-center justify-content-center theme-bg-light">
									  <div class="position-absolute theme-cl h5 mb-0"><i class="fas fa-at"></i></div>
									</div>
									<div class="mr-3 mr-md-4">
									  <h4>پست الکترونیکی</h4>
									  <p>
										{{request.superuser.email}}
									  </p>
									</div>
								  </li>
								   <li class="d-flex align-items-start my-3 my-md-4">
									<div class="rounded-circle p-3 p-sm-4 d-flex align-items-center justify-content-center theme-bg-light">
									  <div class="position-absolute theme-cl h5 mb-0"><i class="fas fa-phone-alt rotate-img"></i></div>
									</div>
									<div class="mr-3 mr-md-4">
									  <h4>شماره های تماس</h4>
									  <p>
										09301741497<br>09030368939
									  </p>
									</div>
								  </li>
								</ol>
							</div>
							<a href="{% url 'ticket:response' %}"><button type="button" class="btn btn-info">تیکت های شما</button></a>
						</div>
					</div>
				</div>
			</section>
			
			<!-- <section class="p-0">
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d12964.035018914681!2d51.37892281675605!3d35.67678642487583!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfa!2s!4v1659772013337!5m2!1sfa!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>				
			</section> -->
			<div class="clearfix"></div>
			<!-- ============================ map End ================================== -->
			
            {% include "main/footer.html" %}
	
			
			<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>
			

		</div>
	

		<!-- ============================================================== -->
		<!-- All Jquery -->
		<!-- ============================================================== -->
        <script src="{% static "assets/js/jquery.min.js" %}"></script>
        <script src="{% static "assets/js/popper.min.js" %}"></script>
        <script src="{% static "assets/js/bootstrap.min.js" %}"></script>
        <script src="{% static "assets/js/select2.min.js" %}"></script>
        <script src="{% static "assets/js/slick.js" %}"></script>
        <script src="{% static "assets/js/moment.min.js" %}"></script>
        <script src="{% static "assets/js/daterangepicker.js" %}"></script> 
        <script src="{% static "assets/js/summernote.min.js" %}"></script>
        <script src="{% static "assets/js/metisMenu.min.js" %}"></script>	
        <script src="{% static "assets/js/custom.js" %}"></script>
		<!-- ============================================================== -->
		<!-- This page plugins -->
		<!-- ============================================================== -->		

	</body>

</html>

templates/detail/responses.html
{% load static %}
{% load price_management %}

<!DOCTYPE html>
<html lang="fa">
	
<head>
		<meta charset="utf-8" />
		<meta name="author" content="Themezhub" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>تیکت هات</title>
		
        <!-- Custom CSS -->
        <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">
		
    </head>
    
    <body dir="rtl">

        <!-- ============================================================== -->
        <!-- Main wrapper - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <div id="main-wrapper">
		
            <!-- ============================================================== -->
            <!-- Top header  -->
            <!-- ============================================================== -->
            <!-- Start Navigation -->
			{% include "main/navigation.html" %}
			<!-- End Navigation -->
			<div class="clearfix"></div>
			<!-- ============================================================== -->
			<!-- Top header  -->
			<!-- ============================================================== -->
			
			<!-- ============================ Dashboard: Dashboard Start ================================== -->
			<section class="gray pt-4" style="background-color: whitesmoke">
				<div class="container-fluid">
										
					<div class="row">

				
						<div class="col-lg-3 col-md-3">
							<div class="dashboard-navbar" style="border-radius: 20px;">
								
								<div class="d-user-avater">
									<img src="/{{request.user.profile}}" class="img-fluid avater" alt="">
									<h4>{{request.user.get_full_name}}</h4>
									{% comment %} <span>برنامه نویس ارشد</span> {% endcomment %}
									<div class="elso_syu89">
										<ul>
											<li><a href="https://www.twitter.com/opozex"><i class="ti-twitter"></i></a></li>
											<li><a href="https://www.instagram.com/opozex"><i class="ti-instagram"></i></a></li>
										</ul>
									</div>
									<div class="elso_syu77">
										<div class="one_third"><div class="one_45ic text-warning bg-light-warning"><i class="fas fa-star"></i></div><span>امتیازات</span></div>
										<div class="one_third"><a href="{% url 'account:courses' %}"><div class="one_45ic text-success bg-light-success"><i class="fas fa-file-invoice"></i></div><span>دوره ها</span></a></div>
										<div class="one_third"><div class="one_45ic text-purple bg-light-purple"><i class="fas fa-user"></i></div><span>هنرجویان</span></div>
									</div>
								</div>
								
								<div class="d-navigation">
									<ul id="side-menu">
										<li><a href="{% url 'account:home' %}"><i class="fas fa-th"></i>داشبورد</a></li>
										<li><a href="{% url 'Wallet:wallet' %}" style="font-family: sans-serif;"><i class="fas fa-credit-card"></i>کیف پول ({% if bal == 0 %}0 {% else %}{% format balance %}{% endif %})</a></li>
						
										<li class="active"><a href="{% url "ticket:ticket" %}"><i class="fas fa-comment"></i>تیکت</a></li>
										<li>
											<a href="{% url 'account:courses' %}"><i class="fas fa-shopping-cart"></i>دوره های خریداری شده</a>
										
										</li>
										<li>
											<a href="{% url 'account_email' %}"><i class="fas fa-envelope"></i>تغییر ایمیل</a>
											
										</li>
										<li>
											<a href="{% url 'account:status' %}"><i class="fas fa-history"></i>تاریخچه ی خرید و انتقالات</a>
											
										</li>
									
										<li>
											<a href="{% url 'account_change_password' %}"><i class="fas fa-key ml-1 rotate-img"></i>تغییر رمز عبور</span></a>
											
										</li>
										<li>
											<form action="{% url 'account:logout' %}" method="post">
												{% csrf_token %}
												<button type="submit" class="btn btn-danger">Logout</button>
											</form>
										</li>
									</ul>
								</div>
								
							</div>
						</div>
												<div class="col-lg-9 col-md-9 col-sm-12">
							
							<!-- Row -->
							<div class="row justify-content-between">
								<div class="col-lg-12 col-md-12 col-sm-12 pb-4">
									<div class="dashboard_wrap d-flex align-items-center justify-content-between">
										<div class="arion">
											<nav class="transparent">
												<ol class="breadcrumb">
													<li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
													<li class="breadcrumb-item active" aria-current="page">تیکت های شما</li>
												</ol>
											</nav>
										</div>
									</div>
								</div>
							</div>
							<!-- /Row -->
							
							<div class="row">
								<div class="col-xl-12 col-lg-12 col-md-12">
									<div class="dashboard_wrap">
										
										<div class="row">
											<div class="col-xl-12 col-lg-12 col-md-12 mb-4">
												<h6 class="m-0">تیکت های شما</h6>
											</div>
										</div>
										
										<div class="row">
											<div class="col-xl-12 col-lg-12 col-md-12 mb-2">
												<div class="table-responsive">
													<table class="table dash_list">
														<thead>
															<tr>
																<th scope="col">#</th>
																<th scope="col">عنوان</th>

																<th scope="col">وضعیت</th>
																 <th scope="col">مشاهده</th>
															</tr>
														</thead>
														<tbody>
															{% for value in ti %}
                                                            
															<tr>
                                                                <th scope="row">{{forloop.counter}}</th>
                                                                
															<td><a href="#"><h6>{{value.subject}}</h6></a></td>
																<td><span class="trip theme-bg-light" style="font-size:15px">{% if value.admin == None %}پاسخ داده نشده {% else %}پاسخ داده شد{% endif %}</span></td>
                                                                
                                                                <td>{% if value.admin == None %} <button class="btn btn-success" disabled>مشاهده</button> {% else %}<a href="{% url 'ticket:ticker' value.id %}"><button class="btn btn-success" >مشاهده</button></a>{% endif %}</td>

															</tr>
															{% endfor %}
														</tbody>
													</table>
												</div>
											</div>
										</div>
										
									</div>
								</div>
							</div>
							
							
						</div>
					
					</div>
					
				</div>
			</section>
			<!-- ============================ Dashboard: Dashboard End ================================== -->
  
		<!-- ============================ Call To Action ================================== -->
		{% include 'main/footer.html' %}
			<!-- ============================ Footer End ================================== -->
			
		
			
			<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>
			

		</div>

		<!-- ============================================================== -->
		<!-- End Wrapper -->
		<!-- ============================================================== -->
  
		<!-- ============================================================== -->
		<!-- All Jquery -->
		<!-- ============================================================== -->

		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="{% static '/assets/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/popper.min.js' %}"></script>

		<script type="text/javascript" src="{% static '/assets/js/select2.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/slick.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/moment.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/daterangepicker.js' %}"></script> 
		<script type="text/javascript" src="{% static '/assets/js/summernote.min.js' %}"></script>
		<script type="text/javascript" src="{% static '/assets/js/metisMenu.min.js'  %}"></script>	
		<script type="text/javascript" src="{% static '/assets/js/custom.js' %}"></script>
		<!-- ============================================================== -->
		<!-- This page plugins -->
		<!-- ============================================================== -->		

	</body>

</html>